function text1(roomcode, updateRoom, setAllDead) {
  let words = [
      "popo",
      "dodo",
      "bidet",
      "pouet",
      "zinzin",
      "chien",
      "chat",
      "maison",
      "table",
      "chaud",
      "froid",
      "banal",
      "plage",
      "poule",
      "tasse",
      "clown",
      "gogos",
      "bouse",
      "groin",
      "gloup",
      "baffe",
      "livre",
      "nuit",
      "croco",
      "niais",
      "dinde",
      "lune",
      "rouge",
      "bleue",
      "blanc",
      "jaune",
      "vert",
      "rire",
      "pleur",
      "singe",
      "bambin",
      "fifou",
      "tarte",
      "crazy",
      "coucou",
      "boule",
      "tigre",
      "pomme",
      "poire",
      "banane",
      "neige",
      "pluie",
      "nuage",
      "soleil",
      "vent",
      "mince",
      "moche",
      "sage",
      "fou",
      "luron",
      "bongo",
      "zigue",
      "kaput",
      "malin",
      "calme",
      "rude",
      "gentil",
    ];

    setAllDead(roomcode)

  updateRoom(roomcode, {
    status: "play",
    countdown: 5,
    time: 5,
    type: "text1",
    infos: {
      mot: words[Math.floor(Math.random() * words.length)],
    },
  });
}

module.exports = text1;
